# yamllint disable rule:line-length
---
name: setup environment

description: load values from 1password vault

inputs:

  instance:
    description: input value that can be used to control which actions are run
    required: false
    default: ""

runs:
  using: "composite"

  steps:

    - name: load values from 1password vault
      uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0    # v2.0.0
      with:
        export-env: true
      env:
        DOCKER_LOGIN: op://platform/svc-dockerhub/username
        DOCKER_PASSWORD: op://platform/svc-dockerhub/password
        SNYK_TOKEN: op://platform/svc-snyk/api-token
        COSIGN_PASSWORD: op://platform/svc-cosign/passphrase
        GREN_GITHUB_TOKEN: op://platform/svc-github/access-token
        SLACK_BOT_TOKEN: op://platform/svc-slack/post-bot-token

    - name: load cosign public key
      uses: ThoughtWorks-DPS/1password-action/write-to-file@2f0a75fadf187f444c855270f8ae09a5c95747d0     # v0.2.3
      with:
        op-value: platform/svc-cosign-public-key/notesPlain
        out-file: cosign.pub

    - name: load cosign key
      uses: ThoughtWorks-DPS/1password-action/write-to-file@2f0a75fadf187f444c855270f8ae09a5c95747d0     # v0.2.3
      with:
        op-value: platform/svc-cosign-private-key/notesPlain
        out-file: cosign.key

    - name: generate release notess
      shell: bash
      run: |
        ls -la
        cat tpl/release-notes.tpl > release-notes.md
        echo ${{ inputs.instance }} >> release-notes.md
        echo "</details>" >> release-notes.md
