# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: development build and release

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:

  alpine-dev-release:
    name: development build and release of alpine image
    uses: twplatformlabs/gha-tools-action/.github/workflows/job-container-dev-release.yaml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image: gha-container-base-image
      organization: twdps
      opencontainer-labels: true
      before-static-analysis: true
      snyk-scan: true
      snyk-severity-threshold: medium
      snyk-organization: twdps
      bats-test: true
      bats-run-container-name: gha-container-base-image
      bats-entry-point: /bin/ash
      bats-test-path: test/gha-container-base-image.bats

  # ubuntu-22-dev-release:
  #   name: development build and release of ubuntu.2204 image
  #   uses: twplatformlabs/gha-tools-action/.github/workflows/job-container-dev-release.yaml@main
  #   secrets:
  #     OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  #   with:
  #     dockerfile: Dockerfile.ubuntu.22
  #     organization: twdps
  #     image: gha-container-base-image
  #     tag-annotation: 22.04-
  #     opencontainer-labels: true
  #     before-static-analysis: true
  #     snyk-scan: true
  #     snyk-severity-threshold: medium
  #     snyk-organization: twdps
  #     security-scan-nofail: true
  #     bats-test: true
  #     bats-run-container-name: gha-container-base-image
  #     bats-entry-point: /bin/bash
  #     bats-test-path: test/gha-container-base-image-ubuntu-22.bats

  # ubuntu-24-dev-release:
  #   name: development build and release of ubuntu.2404 image
  #   uses: ThoughtWorks-DPS/gha-tools-action/.github/workflows/job-container-dev-release.yaml@main
  #   secrets:
  #     OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  #   with:
  #     dockerfile: Dockerfile.ubuntu.24
  #     image: twdps/gha-container-base-image
  #     tag-annotation: ubuntu-24.
  #     opencontainer-labels: true
  #     before-static-analysis: true
  #     snyk-scan: true
  #     snyk-severity-threshold: medium
  #     snyk-organization: twdps
  #     bats-test: true
  #     bats-run-container-name: gha-container-base-image
  #     bats-entry-point: /bin/bash
  #     bats-test-path: test/gha-container-base-image-ubuntu-24.bats
